### ISSUE TITLE
Querying for a non-existent OID on a target machine causes a non-handled exception to occur

### ISSUE THREAD

**Issue by postables** [exhuma/puresnmp#30]
When querying for a non-existent OID on a target machine, it causes an exception which is not handled properly by puresnmp. 

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/puresnmp-1.1.5-py3.5.egg/puresnmp/pdu.py", line 184, in decode
    return super().decode(data)
  File "/usr/lib/python3.5/site-packages/puresnmp-1.1.5-py3.5.egg/puresnmp/pdu.py", line 89, in decode
    values, data = pop_tlv(data)
  File "/usr/lib/python3.5/site-packages/puresnmp-1.1.5-py3.5.egg/puresnmp/x690/types.py", line 89, in pop_tlv
    value = cls.from_bytes(chunk)
  File "/usr/lib/python3.5/site-packages/puresnmp-1.1.5-py3.5.egg/puresnmp/x690/types.py", line 134, in from_bytes
    return cls.decode(data)
  File "/usr/lib/python3.5/site-packages/puresnmp-1.1.5-py3.5.egg/puresnmp/x690/types.py", line 319, in decode
    value, data = pop_tlv(data)
  File "/usr/lib/python3.5/site-packages/puresnmp-1.1.5-py3.5.egg/puresnmp/x690/types.py", line 89, in pop_tlv
    value = cls.from_bytes(chunk)
  File "/usr/lib/python3.5/site-packages/puresnmp-1.1.5-py3.5.egg/puresnmp/x690/types.py", line 134, in from_bytes
    return cls.decode(data)
  File "/usr/lib/python3.5/site-packages/puresnmp-1.1.5-py3.5.egg/puresnmp/x690/types.py", line 319, in decode
    value, data = pop_tlv(data)
  File "/usr/lib/python3.5/site-packages/puresnmp-1.1.5-py3.5.egg/puresnmp/x690/types.py", line 89, in pop_tlv
    value = cls.from_bytes(chunk)
  File "/usr/lib/python3.5/site-packages/puresnmp-1.1.5-py3.5.egg/puresnmp/x690/types.py", line 134, in from_bytes
    return cls.decode(data)
  File "/usr/lib/python3.5/site-packages/puresnmp-1.1.5-py3.5.egg/puresnmp/pdu.py", line 80, in decode
    raise EmptyMessage('No data to decode!')
puresnmp.exc.EmptyMessage: No data to decode!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_test.py", line 306, in <module>
    analyzer_list, importer_list, import_analyzer_mapping, snmp_statistics = first_run()
  File "main_test.py", line 265, in first_run
    effected_importers = snmp_statistics.gen_effected_importers(import_analyzer_mapping.get_mapping())
  File "main_test.py", line 230, in gen_effected_importers
    backedup_analyzers = self._analyzer_que_lookup()
  File "main_test.py", line 216, in _analyzer_que_lookup
    result = get(ip_address, self.community, snmp_oid)
  File "/usr/lib/python3.5/site-packages/puresnmp-1.1.5-py3.5.egg/puresnmp/__init__.py", line 60, in get
    return multiget(ip, community, [oid], port)[0]
  File "/usr/lib/python3.5/site-packages/puresnmp-1.1.5-py3.5.egg/puresnmp/__init__.py", line 84, in multiget
    raw_response = Sequence.from_bytes(response)
  File "/usr/lib/python3.5/site-packages/puresnmp-1.1.5-py3.5.egg/puresnmp/x690/types.py", line 134, in from_bytes
    return cls.decode(data)
  File "/usr/lib/python3.5/site-packages/puresnmp-1.1.5-py3.5.egg/puresnmp/x690/types.py", line 319, in decode
    value, data = pop_tlv(data)
  File "/usr/lib/python3.5/site-packages/puresnmp-1.1.5-py3.5.egg/puresnmp/x690/types.py", line 89, in pop_tlv
    value = cls.from_bytes(chunk)
  File "/usr/lib/python3.5/site-packages/puresnmp-1.1.5-py3.5.egg/puresnmp/x690/types.py", line 134, in from_bytes
    return cls.decode(data)
  File "/usr/lib/python3.5/site-packages/puresnmp-1.1.5-py3.5.egg/puresnmp/pdu.py", line 186, in decode
    raise NoSuchOID('Nothing found at the given OID (%s)' % exc)
puresnmp.exc.NoSuchOID: Nothing found at the given OID (No data to decode!)

```

**Comment by exhuma** [comment]
It was a design decision to handle missing OIDs this way.

To explain the reasoning behind this: The X.690 standard has a null-type. When accessing an inexisting OID on an SNMP agent, I could have chosen to return `None` instead of raising an exception. But then you could no longer distinguish between the case where the OID exists but returns an X.690 NULL value and the case where the OID does not exist.

In other words, if a call to `get` returns `None` you can't tell whether the SNMP-Agent really returned a NULL value, or you accessed an invalid OID and maybe want to warn the user.

I see no other proper way to handle this differently without causing bugs in the client code later down the line.

I suggest wrapping your call to `get` in a `try ... except ... block` like this:

    from puresnmp.exc import NoSuchOID
    try:
        result = get( ... )
    except NoSuchOID as exc:
        LOG.warning(exc)  # or something similar
        result = None

This way, you as the library end-user has full control over what happens when missing OIDs are encountered.

hth
